app/administracion/urls.py
# -*- encoding: utf-8 -*
from django.conf.urls import url

from app.administracion import views

# **************************************
#
#   url: /administracion/
#   namespace: administracion
#
# **************************************

urlpatterns = [
    url(r'^aspirantes/$', views.AspiranteListView.as_view(), name='aspirantes_list_view'),
    url(r'^aspirantes/(?P<aspirante_id>[\d]+)/$', views.AspiranteTemplateView.as_view(), name='aspirantes_detail'),
    url(r'^aspirantes/(?P<aspirante_id>[\d]+)/update-payment/$', views.UpdatePayment.as_view(), name='aspirantes_update_payment'),

    url(r'^etapas/$', views.Etapa.as_view(), name='etapas'),

    url(r'^nivel-de-demanda/$', views.MunicipioListView.as_view(), name='list_municipios'),

    url(r'^panel-de-control/$', views.AdministracionDashboard.as_view(), name='dashboard'),
    url(r'^panel-de-control/desactivar-oferta/$', views.DesactivarOfertaEducativa.as_view(), name='dashboard_desactivar_oferta'),

    url(r'^planteles/$', views.PlantelListView.as_view(), name='plantel_list'),
    url(r'^planteles/cambiar-responsable/(?P<pk>[\d]+)/$', views.PlantelChangeResponsible.as_view(), name='plantel_responsible'),
    url(r'^planteles/precio/(?P<pk>[\d]+)/$', views.PlantelUpdateView.as_view(), name='plantel_precio'),

    url(r'^revisiones/aforo/$', views.RevisionAforoListView.as_view(), name='revision_aforo'),
    url(r'^revisiones/aforo/aceptar/(?P<pk>[\d]+)/$', views.AceptarAforoView.as_view(), name='aforo_aceptar'),
    url(r'^revisiones/aforo/impresion/(?P<pk>[\d]+)/$', views.ImpresionAforoView.as_view(), name='impresion_aforo'),
    url(r'^revisiones/aforo/motivo-rechazo/$', views.GuardarMotivoRechazo.as_view(), name='aforo_motivo_rechazo'),
    url(r'^revisiones/oferta/$', views.RevisionOfertaEducativaListView.as_view(), name='revision_oferta'),
    url(r'^revisiones/oferta/subsistema/(?P<subsistema_id>[\d]+)/$', views.RevisionOfertaEducativaSubsistemaListView.as_view(), name='revision_oferta_subsistema'),
    url(r'^revisiones/oferta/subsistema/(?P<subsistema_id>[\d]+)/comparativa/$', views.CompararOfertaEducativaView.as_view(), name='revision_oferta_comparar'),
    url(r'^revisiones/oferta/subsistema/(?P<revision_id>[\d]+)/aceptar/$', views.AceptarOfertaEducativaView.as_view(), name='revision_oferta_aceptar'),
    url(r'^revisiones/oferta/subsistema/rechazar/$', views.RechazarOfertaEducativa.as_view(), name='revision_oferta_rechazar'),

    url(r'^sedesalternas/$', views.SedesListView.as_view(), name='sedes_list'),
    url(r'^sedesalternas/nuevo/$', views.SedesCreateView.as_view(), name='sedes_create'),
    url(r'^sedesalternas/editar/(?P<pk>[\d]+)/$', views.SedesEditView.as_view(), name='sedes_edit'),

    url(r'^subsistemas/$', views.SubsistemaListView.as_view(), name='subsistemas_list'),
    url(r'^subsistemas/nuevo$', views.SubsistemaCreateView.as_view(), name='subsistemas_create'),
    url(r'^subsistemas/editar/(?P<pk>[\d]+)/$', views.SubsistemaUpdateView.as_view(), name='subsistemas_update'),

    url(r'^usuarios/$', views.UsuarioListView.as_view(), name='users'),
    url(r'^usuarios/nuevo/$', views.UsuarioCreateView.as_view(), name='new_user'),
    url(r'^usuarios/cambiar-contrasena/(?P<pk>[\d]+)/$', views.UpdatePassword.as_view(), name='update_password'),
    url(r'^usuarios/(?P<pk>[\d]+)/$', views.UserUpdateView.as_view(), name='update_user'),

    url(r'^configuraciones/miscelaneos/$', views.MiscelaneosView.as_view(), name='miscelaneos'),

    url(r'^configuraciones/enlaces/$', views.EnlacesListView.as_view(), name='enlaces'),
    url(r'^configuraciones/enlaces/nuevo$', views.EnlaceCreateView.as_view(), name='enlaces_create'),
    url(r'^configuraciones/enlaces/editar/(?P<pk>[\d]+)/$', views.EnlaceEditView.as_view(), name='enlaces_edit'),
    url(r'^configuraciones/enlaces/eliminar/(?P<pk>[\d]+)/$', views.EnlaceDeleteView.as_view(), name='enlaces_delete'),
]

app/billy/urls.py
# -*- encoding: utf-8 -*
from django.conf.urls import url
from app.billy import views

# **************************************
#
#   url: /billy/
#   namespace: billy
#
# **************************************

urlpatterns = [
    url(r'^salario-minimo/nuevo/$', views.SalarioMinimoView.as_view(), name='create_salario_minimo'),
    url(r'^concepto/actualizar/$', views.PaemsConceptoView.as_view(), name='update_concepto_paems'),
]

app/planteles/urls.py
# -*- encoding: utf-8 -*
from django.conf.urls import url

from app.planteles import views


# **************************************
#
#   url: /plantel/
#   namespace: planteles
#
# **************************************

urlpatterns = [
    url(r'^$', views.PLantelHomeView.as_view(), name='home'),
    url(r'^aspirantes/sin-pago-efectuado/$', views.AspirantesSinPagoTemplateView.as_view(), name='aspirante_sin_pago_efecutado'),
    url(r'^(?P<plantel_id>[\d]+)/oferta/$', views.OfertaView.as_view(), name='oferta'),
]

exameneducacionmedia/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from app.accounts.views import LoginRedirectView, LogoutRedirectView
from exameneducacionmedia import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^', include('app.home.urls', namespace='home')),

    url(r'^administracion/', include('app.administracion.urls', namespace='administracion')),
    url(r'^administracion/', include('app.staff.urls', namespace='administracion')),
    url(r'^aspirantes/', include('app.aspirantes.urls', namespace='aspirantes')),
    url(r'^accounts/', include('app.accounts.urls', namespace='accounts')),
    url(r'^planteles/', include('app.planteles.urls', namespace='planteles')),
    url(r'^reportes/', include('app.reportes.urls', namespace='reportes')),
    url(r'^subsistemas/', include('app.subsistemas.urls', namespace='subsistemas')),

    url(r'^mgeo/', include('app.mgeo.urls', namespace='mgeo')),
    url(r'^login/$', LoginRedirectView.as_view(), name='redirect_to_login'),
    url(r'^logout/$', LogoutRedirectView.as_view(), name='redirect_to_logout'),

    url(r'^billy/', include('app.billy.urls', namespace='billy')),

    url(r'^finanzas/', include('app.finanzas.urls', namespace='finanzas')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/planteles/forms.py
# -*- encoding: utf-8 -*

app/administracion/views.py
from django.shortcuts import render, render_to_response
from django.views.generic import View


# Create your views here.
class Inicio(View):

	def get(self, request):
		return render_to_response("inicio.html")

app/administracion/views/aspirantes.py
# -*- encoding: utf-8 -*
from datetime import datetime
from django.http import Http404
from django.http import HttpResponse
from django.http import JsonResponse
from django.views import generic

from app.administracion.models import RevisionRegistro, Revision
from app.aspirantes.models import Aspirante
from app.billy.models import SolicitudPago
from general.mixins import LoginRequiredMixin, GroupRequiredMixin


class AspiranteListView(LoginRequiredMixin, GroupRequiredMixin, generic.ListView):
    group_required = ('departamento', 'plantel',)
    model = Aspirante
    template_name = 'aspirantes/list.html'
    context_object_name = 'aspirantes'

    def get_queryset(self):
        request = self.request

        if request.GET:
            first_name = request.GET.get('first_name', None)
            last_name = request.GET.get('last_name', None)
            term = request.GET.get('term', None)
            referencia_de_pago = request.GET.get('referencia', None)
            return self.model.get_aspirante(first_name, last_name, term, referencia_de_pago)
        return self.model.objects.none()

    def get_context_data(self, **kwargs):
        context = super(AspiranteListView, self).get_context_data(**kwargs)
        total = self.model.objects.count()
        context.update({'aspirantes_total': total})
        return context


class AspiranteTemplateView(LoginRequiredMixin, GroupRequiredMixin, generic.DetailView):
    group_required = 'departamento'
    template_name = 'aspirantes/aspirante.html'
    model = Aspirante
    aspirante = None
    pk_url_kwarg = 'aspirante_id'
    context_object_name = 'aspirante'
    queryset = Aspirante.objects.select_related('usuario',
                                                'domicilio',
                                                'domicilio__localidad',
                                                'informacion_de_procedencia_related',
                                                'revision_aspirante_related',
                                                'revision_aspirante_related__revision__usuario_apertura',
                                                'revision_aspirante_related__revision__usuario_revision').prefetch_related('seleccion_oferta_educativa__oferta_educativa__plantel',
                                                                                                                           'seleccion_oferta_educativa__oferta_educativa__especialidad').all()

    def get_object(self, queryset=None):
        queryset = self.get_queryset()
        try:
            self.aspirante = queryset.get(pk=self.kwargs[self.pk_url_kwarg])
            return self.aspirante
        except Aspirante.DoesNotExist:
            raise Http404

    def get_context_data(self, **kwargs):
        context = super(AspiranteTemplateView, self).get_context_data(**kwargs)
        solicitud_pago = None
        revision = None
        if hasattr(self.aspirante, 'revision_aspirante_related'):
            revision = self.aspirante.revision_aspirante_related
            solicitud_pago = SolicitudPago.objects.select_related('referencia_pago',
                                                                  'concepto',
                                                                  'salario_minimo',
                                                                  'deposito',
                                                                  'deposito__reporte_deposito',
                                                                  'deposito__reporte_deposito__banco').get(pk=revision.solicitud_pago)

        context.update({'solicitud_pago': solicitud_pago, 'revision': revision})
        return context


class UpdatePayment(LoginRequiredMixin, GroupRequiredMixin, generic.View):
    group_required = 'departamento'

    def post(self, request, aspirante_id):
        is_valid = False
        msg = None

        try:
            revision = RevisionRegistro.objects.get(aspirante=aspirante_id, estado=Revision.ESTADO_EN_REVISION, pago_efectuado=False)

            revision.pago_efectuado = True
            revision.fecha_revision = datetime.today()
            revision.estado = Revision.ESTADO_ACEPTADO
            revision.comentario = "El usuario {0} cambió el pago efectuado".format(request.user.username)
            revision.usuario_revision = request.user
            revision.save()
            is_valid = True
        except RevisionRegistro.DoesNotExist:
            msg = "El aspirante ya tiene su pago efectuado o no existe"
        except Exception as e:
            msg = e.message

        return JsonResponse({'is_valid': is_valid, 'msg': msg})

app/administracion/views/dashboard.py
# -*- encoding: utf-8 -*
import datetime

from django.contrib import messages
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import generic

from app.administracion.models import EtapaProceso, RevisionOfertaEducativa, Revision, RevisionAforo
from app.aspirantes.models import Aspirante
from app.planteles.models import OfertaEducativa, Plantel
from general.mixins import GroupRequiredMixin, LoginRequiredMixin


class AdministracionDashboard(LoginRequiredMixin, GroupRequiredMixin, generic.TemplateView):
    group_required = 'departamento'
    template_name = "dashboard/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super(AdministracionDashboard, self).get_context_data(**kwargs)
        today = datetime.date.today()
        etapa_oferta = EtapaProceso.objects.get(nombre='OFERTA')

        oferta_educativa = OfertaEducativa.objects.filter(activa=True).count()
        planteles = Plantel.objects.all()
        new_members = Aspirante.objects.select_related().filter(usuario__date_joined__day=today.day,
                                                                usuario__date_joined__month=today.month,
                                                                usuario__date_joined__year=today.year).count()

        planteles_list = Plantel.demanda_capacida_porcentaje()
        context.update({
            'planteles':            planteles.count(),
            'new_members':          new_members,
            'planteles_list':       planteles_list,
            'aforo_revision':       RevisionAforo.objects.filter(estado=Revision.ESTADO_EN_REVISION).count(),
            'is_etapa_oferta':      True if etapa_oferta.apertura <= today else False,
            'oferta_revision':      RevisionOfertaEducativa.objects.filter(estado=Revision.ESTADO_EN_REVISION).count(),
            'oferta_educativa':     oferta_educativa,
            'planteles_list_count': len(list(planteles_list))
        })
        return context


class DesactivarOfertaEducativa(LoginRequiredMixin, GroupRequiredMixin, generic.View):
    group_required = 'departamento'

    def post(self, request):
        transaction.set_autocommit(False)
        try:
            etapa_oferta = EtapaProceso.objects.get(nombre='OFERTA')
            today = datetime.date.today()
            if etapa_oferta.apertura <= today:
                raise Exception("La etapa de oferta ya inició por lo tanto no se puede desactivar la oferta educativa")
            oferta = OfertaEducativa.objects.all()
            for item in oferta:
                item.activa = False
                item.save()
            transaction.commit()
            messages.success(request, 'La oferta se reinició correctamente')
            return HttpResponseRedirect(reverse('administracion:dashboard'))
        except Exception as e:
            transaction.rollback()
            messages.warning(request, e.message)
            return redirect(request.META.get('HTTP_REFERER'))

app/administracion/views/folios_ceneval.py
# -*- encoding: utf-8 -*

app/administracion/views/miscelaneos.py
# -*- encoding: utf-8 -*
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import generic

from app.administracion.models import Configuracion


class MiscelaneosView(generic.View):
    template_name = "miscelaneos/miscelaneos.html"

    def get_context(self):
        miscelaneos = Configuracion.objects.all()
        context = {'miscelaneos': miscelaneos}
        return context

    def get(self, request):
        context = self.get_context()
        return render(request, self.template_name, context)

    def post(self, request):
        transaction.set_autocommit(False)
        try:
            for configuracion in Configuracion.objects.all():
                valor = request.POST['row_id_%s' % configuracion.id]
                try:
                    configuracion.valor = valor if valor != '' else None
                    configuracion.save()
                except ValueError:
                    raise Exception('No se pudo guardar la configuracion de %s', configuracion.descripcion)

            transaction.commit()
            return HttpResponseRedirect(reverse('administracion:miscelaneos'))
        except Exception as e:
            context = self.get_context()
            context.update({'errors': e})
            transaction.rollback()
            return render(request, self.template_name, context)

app/administracion/views/nivel_demanda.py
# -*- encoding: utf-8 -*
from django.contrib import messages
from django.shortcuts import redirect
from django.views import generic

from app.mgeo.models import Municipio, NivelDeDemanda
from general.mixins import LoginRequiredMixin, NeedsDepartamentoGroupAccessMixin


class MunicipioListView(LoginRequiredMixin, NeedsDepartamentoGroupAccessMixin, generic.ListView):
    model = NivelDeDemanda
    template_name = "nivel_demanda/list.html"
    context_object_name = "municipios"

    def get_queryset(self):
        return self.model.objects.select_related('cabecera').filter(entidad_federativa__id=23)

    def post(self, request):
        municipio = self.model.objects.get(pk=request.POST.get('municipio'))
        municipio.nivel_de_demanda = request.POST.get('nivel_demanda')
        municipio.save()
        messages.add_message(request, messages.INFO, 'El nivel de demanda se actualizó correctamente')
        return redirect(request.META.get('HTTP_REFERER'))

app/planteles/views/aspirantes.py
# -*- encoding: utf-8 -*
from django.views import generic

from app.planteles.utils import PlantelUtils


class AspirantesSinPagoTemplateView(PlantelUtils, generic.TemplateView):
    template_name = 'aspirantes/sin_pago_efectuado.html'

    def get_context_data(self, **kwargs):
        context = super(AspirantesSinPagoTemplateView, self).get_context_data(**kwargs)
        plantel = self.plantel
        aspirantes_sin_pago = plantel.aspirantes_sin_pago_completado()
        context.update({
            'plantel':                   plantel,
            'aspirantes_sin_pago':       aspirantes_sin_pago,
            'aspirantes_sin_pago_count': len(list(aspirantes_sin_pago))
        })
        return context

app/administracion/templates/planteles/change_responsible.html
{% extends 'base_administracion.html' %}

{% block extra_head %}
{% endblock %}

{% block page_header %}
	Cambiar responsable
{% endblock %}

{% block optional_description %}
	<small>Plantel</small>
{% endblock %}

{% block html %}
	<div class="content">
		{% if messages %}
			<div class="row">
				<div class="col-md-6">
					{% include "messages_tags.html" %}
				</div>
			</div>
		{% endif %}
		<div class="row">
			<div class="col-md-6">
				<div class="box">
					<div class="box-header with-border">
						<h3 class="box-title">Asignar responsable</h3>
					</div><!-- /.box-header -->
					<div class="box-body">
						<form method="post">
							{% csrf_token %}
							<input type="hidden" name="plantel_id" value="{{ plantel_id }}">
							<input type="hidden" name="group_id" value="{{ group.pk }}">
							<p>
								<label for="">Nombre(s)</label>
								<input type="text" name="first_name" class="form-control" required>
							</p>
							<p>
								<label for="">Apellidos</label>
								<input type="text" name="last_name" class="form-control" required>
							</p>
							<p>
								<label for="">Correo electrónico</label>
								<input type="email" name="email" class="form-control" required>
							</p>
							<p>
								<label for="">Usuario</label>
								<input type="text" name="username" class="form-control" required>
							</p>
							<p>
								<label for="">Contraseña</label>
								<input type="password" name="password" class="form-control">
							</p>
							<p>
								<button type="submit" class="btn btn-primary">Guardar</button>
								<a href="{% url 'administracion:plantel_list' %}" class="btn btn-default pull-right">Regresar</a>
							</p>
						</form>
					</div><!-- /.box-body -->
				</div><!-- /.box -->
			</div>
		</div>
	</div>
{% endblock %}

{% block extra_scripts %}
{% endblock %}

app/administracion/templates/planteles/list.html
{% extends 'base_administracion.html' %}

{% load staticfiles %}
{% load administracion_extras %}

{% block extra_head %}
	<link rel="stylesheet" href="{% static "css/misc.css" %}">
	<link rel="stylesheet" href="{% static "bower/seiyria-bootstrap-slider/dist/css/bootstrap-slider.min.css" %}">
{% endblock %}

{% block page_header %}
	Planteles
{% endblock %}

{% block optional_description %}
	<small>Lista</small>
{% endblock %}

{% block html %}
	<section class="content">
		{% if messages %}
			{% include "messages_tags.html" %}
		{% endif %}
		<div class="row">
			<div class="col-md-12">
				<div class="box">
					<div class="box-header with-border">
						<h3 class="box-title">Concepto y salario mínimo</h3>
					</div><!-- /.box-header -->
					<div class="box-body no-padding">
						<table class="table table-striped">
							<thead>
								<tr>
									<th>Concepto</th>
									<th width="15%" class="text-right">Salario mínimo activo</th>
									<th width="15%" class="text-right">Cantidad de salario mínimo</th>
									<th width="5%" class="text-right">Total</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>{{ concepto.descripcion }}</td>
									<td class="text-right">
										<form action="{% url 'billy:create_salario_minimo' %}" method="post">
											{% csrf_token %}
											<input type="text" class="form-control text-right" name="monto" value="{{ salario_minimo.monto }}">
										</form>
									</td>
									<td class="text-right">
										<form action="{% url 'billy:update_concepto_paems' %}" method="post">
											{% csrf_token %}
											<input type="text" class="form-control text-right" name="salarios_minimos" value="{{ concepto.salarios_minimos }}">
										</form>
									</td>
									<td class="text-right">
										<strong>${{ total }}.00</strong>
									</td>
								</tr>
							</tbody>
						</table>
					</div><!-- /.box-body -->
				</div><!-- /.box -->
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="box">
					<div class="box-header with-border">
						<h3 class="box-title">Planteles</h3>
						<div class="box-tools">
							<div class="row">
								<div class="col-md-4 pull-right">
									<form role="search">
										<div class="input-group">
											<input type="text" class="form-control col-md-6" placeholder="Nombre ó CCT"
												   name="search">
											<div class="input-group-btn">
												<button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i>
												</button>
											</div>
										</div>
									</form>
								</div>

								<div class="col-md-3 pull-right">
									<div class="dropdown pull-right">
										<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1"
												data-toggle="dropdown">
											Seleccionar subsistema
											<span class="caret"></span>
										</button>
										<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
											{% for subsistema in subsistemas %}
												<li role="presentation"><a role="menuitem" tabindex="-1"
																		   href="{% url 'administracion:plantel_list' %}?subsistema={{ subsistema.pk }}">{{ subsistema }}</a>
												</li>
											{% endfor %}
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div><!-- /.box-header -->
					<div class="box-body no-padding">
						<table class="table table-hover">
							<thead>
								<tr>
									<th>#</th>
									<th>Plantel</th>
									<th>CCT</th>
									<th>Subsistema</th>
									<th>Responsable</th>
									<th width="20%">Descuento</th>
									<th class="text-right" width="10%">Precio</th>
								</tr>
							</thead>
							<tbody>
								{% for plantel in planteles %}
									<tr>
										<td>{{ forloop.counter }}</td>
										<td>{{ plantel.referencia }}</td>
										<td>{{ plantel.cct }}</td>
										<td>{{ plantel.subsistema.referencia }}</td>
										<td>
											<div class="dropdown">
												<button class="btn btn-default btn-block dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
													{{ plantel.responsable.get_full_name }} <span class="caret"></span>
												</button>
												<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
													<li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'administracion:plantel_responsible' plantel.pk %}">Cambiar</a></li>
												</ul>
											</div>
										</td>
										<td>
											<form action="{% url 'administracion:plantel_precio' plantel.pk %}"
												  method="post" class="form-horizontal"
												  id="subsistema-form" data-form="plantel_{{ plantel.pk }}">
												{% csrf_token %}

												<input data-total="{{ total }}" data-plantel="plantel_{{ plantel.pk }}"
													   data-slider-id='discount-slider' type="text" data-slider-min="0"
													   data-slider-max="100" data-slider-step="1" data-slider-value="{{ plantel.descuento }}"
													   name="precio"/>
												<span><span data-label="plantel_{{ plantel.pk }}">{{ plantel.descuento }}%</span></span>

											</form>
										</td>
										<td>
											<div class="input-group">
												<span class="input-group-addon">$</span>
												<input class="text-right form-control" data-precio="plantel_{{ plantel.pk }}" name="precio" id="precio"
													   value="{% plantel_precio plantel.descuento total %}" required>
											</div>
										</td>
									</tr>
								{% empty %}
									<tr>
										<td colspan="4">Sin resultados</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
					</div><!-- /.box-body -->
					<div class="box-footer">
						<label class="pull-right"><strong></strong></label>
					</div><!-- box-footer -->
				</div><!-- /.box -->
			</div>
		</div>
	</section>
{% endblock %}

{% block extra_scripts %}
	<script type="text/javascript" src="{% static "bower/seiyria-bootstrap-slider/dist/bootstrap-slider.min.js" %}"></script>
	<script type="text/javascript" src="{% static "bower/remarkable-bootstrap-notify/dist/bootstrap-notify.min.js" %}"></script>
	<script type="text/javascript" src="{% static "planteles/js/list.js" %}"></script>
{% endblock %}