app/accounts/urls.py
# -*- encoding: utf-8 -*
from django.conf.urls import url

from app.accounts import views

# **************************************
#
#   url: /accounts/
#   namespace: accounts
#
# **************************************

urlpatterns = [
	url(r'^login/$', views.LoginFormView.as_view(), name='login'),
	url(r'^logout/$', views.logout, name='logout'),
	url(r'^change-password/$', views.ChangePasswordUser.as_view(), name='change_password'),
]

app/aspirantes/urls.py
# -*- encoding: utf-8 -*
from django.conf.urls import url

from app.aspirantes import views

# **************************************
#
#   url: /aspirante/
#   namespace: aspirantes
#
# **************************************

urlpatterns = [
    url(r'^$', views.DashboardView.as_view(), name='dashboard'),

    url(r'^api/get-planteles-by/$', views.get_json_plantel_by, name='api_get_planteles_by'),
    url(r'^api/get-especialidades-by/$', views.get_json_especialidad_by, name='api_get_especialidades_by'),
    url(r'^api/get-aspirante-opciones-educativas/$', views.get_json_aspirante_opciones_educativas, name='api_get_aspirante_opciones_educativas'),

    url(r'^cuestionario/$', views.CrearCuestionarioEnBlanco.as_view(), name='create_blank_survey'),
    url(r'^cuestionario/responder/$', views.PreguntaListView.as_view(), name='respond_survey'),
    url(r'^cuestionario/respuesta/$', views.CuestionarioContextoCreate.as_view(), name='save_answer'),

    url(r'^enviar-registro/$', views.EnviarRegistro.as_view(), name='enviar_registro'),
    url(r'^ficha-deposito/$', views.FichaDeposito.as_view(), name='ficha_deposito'),
    url(r'^pase-examen/generar/$', views.PaseAlExamen.as_view(), name='pase_al_examen'),
    url(r'^pase-examen/descargar/$', views.FichaDeRegistro.as_view(), name='ficha_de_registro'),


    url(r'^perfil/$', views.ProfileView.as_view(), name='profile'),
    url(r'^perfil/datos-generales/$', views.ApplicantGeneralData.as_view(), name='profile_basic_info'),
    url(r'^perfil/update-email/$', views.UpdateApplicantEmail.as_view(), name='profile_email'),
    url(r'^perfil/update-password/$', views.UpdateApplicantPassword.as_view(), name='profile_password'),
    url(r'^perfil/domicilio/$', views.AspiranteDomicilioView.as_view(), name='save_address'),
    url(r'^perfil/domicilio/actualizar$', views.AspiranteDomicilioUpdateView.as_view(), name='update_address'),
    url(r'^perfil/informacion-procedencia/$', views.InformacionProcedenciaCreateView.as_view(), name='informacion_procedencia'),
    #url(r'^perfil/domicilio/$', '', name='profile_address'),
    #url(r'^perfil/informacion-de-procedencia/$', '', name='profile_informacion_de_procedencia'),

    url(r'^mis-opciones/$', views.MiSeleccionEducativaView.as_view(), name='mis_opciones'),
    url(r'^opciones-educativas/$', views.SeleccionOfertaEducativaView.as_view(), name='opciones_educativas'),

    url(r'^registro/matricula$', views.SignupMatricula.as_view(), name='signup_matricula'),
    url(r'^registro/curp$', views.SignupCurp.as_view(), name='signup_curp'),
    url(r'^registro/extranjero$', views.SignupExtranjero.as_view(), name='signup_extranjero'),
    url(r'^registro/obtener-datos/$', views.BuscarAlumnoEnSiceeb.as_view(), name='search_on_siceeb'),
    url(r'^registro/validar-curp/$', views.ConsultarCurpRenapo.as_view(), name='search_curp')
]

app/home/urls.py
# -*- encoding: utf-8 -*
from django.conf.urls import url

from app.home import views

# **************************************
#
#   url: /
#   namespace: home
#
# **************************************

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^reset-password-confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.PasswordResetConfirmView.as_view(), name='reset_password_confirm'),
    url(r'^reset-password/$', views.ResetPasswordRequestView.as_view(), name='reset_password')
]

exameneducacionmedia/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from app.accounts.views import LoginRedirectView, LogoutRedirectView
from exameneducacionmedia import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^', include('app.home.urls', namespace='home')),

    url(r'^administracion/', include('app.administracion.urls', namespace='administracion')),
    url(r'^administracion/', include('app.staff.urls', namespace='administracion')),
    url(r'^aspirantes/', include('app.aspirantes.urls', namespace='aspirantes')),
    url(r'^accounts/', include('app.accounts.urls', namespace='accounts')),
    url(r'^planteles/', include('app.planteles.urls', namespace='planteles')),
    url(r'^reportes/', include('app.reportes.urls', namespace='reportes')),
    url(r'^subsistemas/', include('app.subsistemas.urls', namespace='subsistemas')),

    url(r'^mgeo/', include('app.mgeo.urls', namespace='mgeo')),
    url(r'^login/$', LoginRedirectView.as_view(), name='redirect_to_login'),
    url(r'^logout/$', LogoutRedirectView.as_view(), name='redirect_to_logout'),

    url(r'^billy/', include('app.billy.urls', namespace='billy')),

    url(r'^finanzas/', include('app.finanzas.urls', namespace='finanzas')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/home/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

app/home/forms.py
# -*- encoding: utf-8 -*
from django import forms


class PasswordResetRequestForm(forms.Form):
    email_or_username = forms.CharField(label="Correo electrónico", max_length=254,
                                        widget=forms.EmailInput(attrs={'class': 'form-control'}))


class SetPasswordForm(forms.Form):
    """
    A form that lets a user change set their password without entering the old
    password
    """
    error_messages = {
        'password_mismatch': "Las contraseñas no coinciden",
    }
    new_password1 = forms.CharField(label="Nueva contraseña",
                                    widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password2 = forms.CharField(label="Confirmar nueva contraseña",
                                    widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
        return password2

app/home/views.py
# -*- encoding: utf-8 -*
import datetime

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import generic
from sparkpost import SparkPost

from app.accounts.forms import LoginAuthenticationForm
from app.administracion.models import EtapaProceso
from app.home.forms import PasswordResetRequestForm, SetPasswordForm
from exameneducacionmedia.settings import SPARKPOST_API_KEY, DEFAULT_FROM_EMAIL
from general.mixins import RedirectMixin


class HomeView(RedirectMixin, generic.View):
    def get(self, request):
        form = LoginAuthenticationForm
        today = datetime.date.today()
        registro = EtapaProceso.objects.get(nombre__exact='REGISTRO')
        is_registro = True if registro.apertura <= today <= registro.cierre else False
        context = {'form': form, 'is_registro': is_registro, 'registro': registro}

        return render(request, "home.html", context)


class ResetPasswordRequestView(generic.FormView):
    template_name = "reset_password/reset_password.html"
    success_url = reverse_lazy("home:home")
    form_class = PasswordResetRequestForm

    @staticmethod
    def validate_email_address(email):

        try:
            validate_email(email)
            return True
        except ValidationError:
            return False

    def reset_password(self, user, request):
        sp = SparkPost(SPARKPOST_API_KEY)

        uid = urlsafe_base64_encode(force_bytes(user.pk))
        token = default_token_generator.make_token(user)
        domain = request.META['HTTP_HOST'],
        url = reverse('home:reset_password_confirm', kwargs={'uidb64': uid, 'token': token})

        response = sp.transmissions.send(
            recipients=[user.email],
            template='siem-reset-passwod',
            from_email=DEFAULT_FROM_EMAIL,
            subject='Restablecimiento de la contraseña en SIEM',
            track_opens=True,
            track_clicks=True,
            transactional=True,
            substitution_data={
                "username":           user.get_username(),
                "user_full_name":     user.get_full_name(),
                "reset_password_url": "http://" + domain[0] + url,
            },
        )
        print(response)

        """
        c = {
            'email':              user.email,
            'domain': request.META['HTTP_HOST'],
            'site_name':          'SIEM',
            'uid':                urlsafe_base64_encode(force_bytes(user.pk)),
            'user':               user,
            'token':              default_token_generator.make_token(user),
            'protocol':           'http',
        }
        print(c)
        subject_template_name = 'profile/reset_password/password_reset_subject.txt'
        # copied from
        # django/contrib/admin/templates/registration/password_reset_subject.txt
        # to templates directory
        email_template_name = 'profile/reset_password/password_reset_email.html'
        # copied from
        # django/contrib/admin/templates/registration/password_reset_email.html
        # to templates directory
        subject = loader.render_to_string(subject_template_name, c)
        # Email subject *must not* contain newlines
        subject = ''.join(subject.splitlines())
        email = loader.render_to_string(email_template_name, c)
        send_mail(subject, email, DEFAULT_FROM_EMAIL,
                  [user.email], fail_silently=False)
        """

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        try:
            if form.is_valid():
                data = form.cleaned_data["email_or_username"]
            # uses the method written above
            if self.validate_email_address(data) is True:
                '''
				If the input is an valid email address, then the following code will lookup for users associated with that email address. If found then an email will be sent to the address, else an error message will be printed on the screen.
				'''
                associated_users = User.objects.filter(
                    Q(email=data) | Q(username=data))
                if associated_users.exists():
                    for user in associated_users:
                        self.reset_password(user, request)

                    result = self.form_valid(form)
                    messages.success(
                        request, 'Se ha enviado un email a {0}. Comprueba tu bandeja de entrada para continuar restableciendo tu contraseña'.format(data))
                    return result
                result = self.form_invalid(form)
                messages.error(
                    request, 'Ningún usuario está asociado con este email')
                return result
            else:
                '''
				If the input is an username, then the following code will lookup for users associated with that user. If found then an email will be sent to the user's address, else an error message will be printed on the screen.
				'''
                associated_users = User.objects.filter(username=data)
                if associated_users.exists():
                    for user in associated_users:
                        self.reset_password(user, request)
                    result = self.form_valid(form)
                    messages.success(
                        request, "Se ha enviado un email a {0}. Comprueba tu bandeja de entrada para continuar restableciendo tu contraseña.".format(data))
                    return result
                result = self.form_invalid(form)
                messages.error(
                    request, 'Este nombre de usuario no existe en el sistema')
                return result
            messages.error(request, 'Entrada inválida')
        except Exception as e:
            print(e)
        return self.form_invalid(form)


class PasswordResetConfirmView(generic.FormView):
    template_name = "reset_password/reset_password.html"
    success_url = reverse_lazy("home:home")
    form_class = SetPasswordForm

    def post(self, request, uidb64=None, token=None, *arg, **kwargs):
        """
        View that checks the hash in a password reset link and presents a
        form for entering a new password.
        """
        UserModel = get_user_model()
        form = self.form_class(request.POST)
        assert uidb64 is not None and token is not None  # checked by URLconf
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = UserModel._default_manager.get(pk=uid)
        except (TypeError, ValueError, OverflowError, UserModel.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            if form.is_valid():
                new_password = form.cleaned_data['new_password2']
                user.set_password(new_password)
                user.save()
                messages.success(request, 'Tu contraseña ha sido restaurada')
                return self.form_valid(form)
            else:
                messages.error(
                    request, 'Tu contraseña no ha sido restaurada')
                return self.form_invalid(form)
        else:
            messages.error(
                request, 'El enlace para restablecer tu contraseña ya no es válido')
            return self.form_invalid(form)

app/planteles/views/home.py
# -*- encoding: utf-8 -*
from django.views import generic

from app.planteles.models import SedeAlterna
from app.planteles.utils import PlantelUtils


class PLantelHomeView(PlantelUtils, generic.TemplateView):
    template_name = 'home/home.html'

    def get_context_data(self, **kwargs):
        context = super(PLantelHomeView, self).get_context_data(**kwargs)
        plantel = self.plantel

        capacidad_total = 0 if plantel.capacidad_total(incluir_sedes_alternas=False) is None else plantel.capacidad_total(incluir_sedes_alternas=False)
        total_aulas = plantel.total_aulas(incluir_sedes_alternas=False)
        capacidad_ocupada = 0 if plantel.capacidad_ocupada(incluir_sedes_alternas=False) is None else plantel.capacidad_ocupada(incluir_sedes_alternas=False)
        oferta_eduacativa_related = plantel.oferta_eduacativa_related.all()
        demanda = plantel.demanda

        try:
            porcentaje_ocupado = int((float(100) / capacidad_total) * capacidad_ocupada)
        except:
            porcentaje_ocupado = 0

        plantel.totales = {
            'capacidad':          capacidad_total,
            'aulas':              total_aulas,
            'capacidad_ocupada':  capacidad_ocupada,
            'oferta_educativa':   oferta_eduacativa_related,
            'demanda':            demanda,
            'porcentaje_ocupado': porcentaje_ocupado
        }

        if SedeAlterna.objects.filter(plantel=plantel).exists():
            plantel.sedes_alternas = SedeAlterna.objects.filter(plantel=plantel).all()
            for sede_alterna in plantel.sedes_alternas:
                capacidad_total = sede_alterna.capacidad_total()
                aulas = sede_alterna.total_aulas()
                capacidad_ocupada = sede_alterna.capacidad_ocupada_1(plantel.id)

                sede_alterna.totales = {
                    'capacidad':          capacidad_total,
                    'aulas':              aulas,
                    'capacidad_ocupada':  capacidad_ocupada,
                    'porcentaje_ocupado': int((float(100) / capacidad_total) * capacidad_ocupada)
                }

        aspirantes_sin_pago = plantel.aspirantes_sin_pago_completado()
        aspirantes_con_proceso_completo = plantel.aspirantes_con_proceso_completo()
        context.update({
            'plantel':             plantel,
            'aspirantes_sin_pago_count': len(list(aspirantes_sin_pago)),
            'aspirantes_con_proceso_completo': len(list(aspirantes_con_proceso_completo))
        })
        return context

app/home/templates/home.html
{% load staticfiles %}
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<link rel="icon" type="image/x-icon" href="{% static "img/iconoseyc.png" %}">
		<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
		<meta name="keywords"
			  content="SEyC, SEQ, SEyQ, Secretaría, Educación, Educacion, Cultura, maestros, docentes, escolar, escuela, becas, alumnos, escuelas arte, música, teatro, danza, gobierno, primaria, secundaria, superior, universidad, becas, padres de familia,Quintana Roo, Chetumal, Cancún, Playa del Carmen, Felipe Carrillo Puerto, Cozumel, Isla Mujeres, paenms, proceso de asignación de espacios, prepa, preparatoria, prepa quintana roo, preparatoria quintana roo">
		<meta name="rights" content="SEyC / SEQ">
		<meta name="description" content="Página oficial del Proceso de Asignación de Espacios Educación Media Superior">
		<title>{% block title %}SIEM - Sistema de Ingreso a la Educación Media.{% endblock %}</title>
		<!-- Tell the browser to be responsive to screen width -->
		<!-- Bootstrap 3.3.6 -->
		<link rel="stylesheet" href="{% static "adminlte/bootstrap/css/bootstrap.min.css" %}">
		<!-- Font Awesome -->
		<link rel="stylesheet" href="{% static "bower/font-awesome/css/font-awesome.min.css" %}">
		<!-- Google Font -->
		<link href="https://fonts.googleapis.com/css?family=Comfortaa|Muli" rel="stylesheet">

		<style>
			body {
				font-family:           'Muli', sans-serif;
				background:            url("{% static "img/03_greca_gris.png" %}");
				background-repeat:     no-repeat;
				background-position:   right top;
				background-attachment: fixed;
			}

			h1, h2, h3, h4, h5, h6 {
				text-align: center;
			}

			h1, h3 {
				color: #484D4D;
			}

			h2 {
				color: #909896;
			}

			h1 {
				font-family: 'Comfortaa', sans-serif;
				font-size:   4.5rem;
			}

			h2 {
				font-size: 2rem;
			}

			h3 {
				font-size: 1.8rem;
			}

			.wrapper {

			}

			.header {
				padding: 1.5rem;
			}

			.content {
			}

			.footer {
			}

			.panel-primary {
				border-color: #00A7D4;
			}

			.panel-primary > .panel-heading {
				background-color: #00A7D4;
				border-color:     #00A7D4;
			}

			.panel-success {
				border-color: #5AAF53;
			}

			.panel-success > .panel-heading {
				background-color: #5AAF53;
				border-color:     #5AAF53;
			}

			.panel-success > .panel-heading > .panel-title {
				color: #fff;
			}

			@media (min-width: 768px) {
				body {

				}
			}

			@media (min-width: 992px) {
				body {
					background:            url("{% static "img/02_grecas.png" %}"), url("{% static "img/03_greca_gris.png" %}");
					background-size:       auto, auto;
					background-repeat:     no-repeat;
					background-position:   left top, right top;
					background-attachment: fixed, fixed;

				}

			}

			@media (min-width: 1200px) {
				body {
					background:            url("{% static "img/07_alumnos_pixlr.png" %}"), url("{% static "img/02_grecas.png" %}"), url("{% static "img/03_greca_gris.png" %}");
					background-size:       contain, auto, auto;
					background-repeat:     no-repeat;
					background-position:   left bottom, left top, right top;
					background-attachment: fixed, fixed, fixed;
				}
			}
		</style>
	</head>
	<body>
		<div class="wrapper">
			<div class="container-fluid header">
				<div class="row">
					<div class="col-xs-12">
						<img src="{% static "img/01_logos.png" %}" class="img-responsive pull-right" alt="">
					</div>
				</div>
			</div>
			<div class="container-fluid content">
				<div class="row">
					<div class="col-xs-12 col-md-6 col-md-offset-6 col-lg-4 col-lg-offset-8">
						<h1>Educación Media Superior</h1>
						<h2>Proceso de Asignación de Espacios</h2>
						<h3>¡Consulta la convocatoria, realiza tu registro, y presenta tu examen CENEVAL!</h3>

						{% if form.errors %}
							<div class="alert alert-info" role="alert">
								<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
								<span class="sr-only">Error:</span>
								Por favor introduzca su usuario y contraseña correctamente.
							</div>
						{% endif %}
						{% if messages %}
							{% include "messages_tags.html" %}
						{% endif %}
					</div>

				</div>

				<div class="row">
					<div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-6 col-lg-4 col-lg-offset-8">
						<h3>Información</h3>
						<nav>
							<ul class="list-group">
								<li class="list-group-item">
									<a href="{% static "media/CONVOCATORIA_PAENMS_2017.pdf" %}" target="_blank">
										Convocatoria PAENMS 2017
										<span class="glyphicon glyphicon-save pull-right" aria-hidden="true"></span>
									</a>
								</li>
								{% comment %}<li class="list-group-item">
								<a href="#">
									Catálogo de preparatorias públicas
									<span class="glyphicon glyphicon-save pull-right" aria-hidden="true"></span>
								</a>
							</li>
							<li class="list-group-item">
								<a href="#">Guía de estudios EXANI-I CENEVAL
									<span class="glyphicon glyphicon-save pull-right" aria-hidden="true"></span>
								</a>
							</li>{% endcomment %}
								<li class="list-group-item">
									<a href="http://www.facebook.com/paenmsqroo" target="_blank">Asesorías y dudas</a>
								</li>
							</ul>
						</nav>
					</div>

				</div>

				<div class="row">
					<div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-6 col-lg-4 col-lg-offset-8">
						<h3>¿No tienes cuenta? ¡Regístrate!</h3>
						<section class="sign-up-links">
							{% include "sign_in_snippet.html" %}
						</section>
					</div>
				</div>

				<div class="row">
					<div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-6 col-lg-4 col-lg-offset-8">
						<div class="panel panel-primary">
							<div class="panel-heading">
								<h3 class="panel-title">Iniciar sesión</h3>
							</div>
							<div class="panel-body">
								<form action="{% url 'accounts:login' %}" method="post">
									{% csrf_token %}
									<div class="form-group has-feedback">
										{{ form.username }}
										<span class="glyphicon glyphicon-envelope form-control-feedback"></span>
									</div>
									<div class="form-group has-feedback">
										{{ form.password }}
										<span class="glyphicon glyphicon-lock form-control-feedback"></span>
									</div>
									<div class="row">
										<div class="col-xs-8">
											<div class="checkbox icheck">
												<label>
													{{ form.rememberme }} Mantener iniciada la sesión
												</label>
											</div>
										</div>
										<!-- /.col -->
										<div class="col-xs-4">
											<button type="submit" class="btn btn-primary btn-block">Entrar</button>
										</div>
										<!-- /.col -->
									</div>
									<div class="row">
										<div class="col-md-12">
											<a href="{% url 'home:reset_password' %}">Olvidé mi contraseña</a>
										</div>
									</div>
								</form>

							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="container-fluid footer">
				<div class="row">
					<div class="col-xs-12">
						<a href="http://www.seyc.gob.mx">
							<img src="{% static "img/05_grecas_pie_con_texto.png" %}" class="img-responsive pull-right" alt="">
						</a>
					</div>
				</div>
			</div>
		</div>

		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
		<script src="{% static "adminlte/plugins/jQuery/jquery-2.2.3.min.js" %}"></script>
		<!-- Include all compiled plugins (below), or include individual files as needed -->
		<script src="{% static "adminlte/bootstrap/js/bootstrap.min.js" %}"></script>
		<script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function () {
                        (i[r].q = i[r].q || []).push(arguments)
                    }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                    m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src   = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-41058288-2', 'auto');
            ga('send', 'pageview');

		</script>
	</body>
</html>

app/home/templates/sign_in_snippet.html
{% if is_registro %}
	<nav>
		<ul class="list-group">
			<li class="list-group-item">
				<a href="{% url 'aspirantes:signup_matricula' %}">
					Estudio o estudié en el Estado de Quintana Roo
				</a>
			</li>
			<li class="list-group-item">
				<a href="{% url 'aspirantes:signup_curp' %}">
					No estudié en el Estado de Quintana Roo, pero tengo CURP (Extranjeros con CURP y otros Estados)
				</a>
			</li>
			<li class="list-group-item">
				<a href="{% url 'aspirantes:signup_extranjero' %}">
					No estudié en el Estado de Quintana Roo y no tengo CURP (Extranjeros sin CURP)
				</a>
			</li>
		</ul>
	</nav>
{% else %}
	<div class="alert alert-info text-center" style="font-size: 1.8rem">
		<strong>El registro inicia del {{ registro.apertura|date:'d \d\e F \d\e\l Y' }} al {{ registro.cierre|date:'d \d\e F \d\e\l Y' }}</strong>
	</div>
{% endif %}