app/subsistemas/urls.py
# -*- encoding: utf-8 -*
from django.conf.urls import url

from app.subsistemas import views

# **************************************
#
#   url: /subsistemas/
#   namespace: subsistemas
#
# **************************************

urlpatterns = [
    url(r'^$', views.StartTemplateView.as_view(), name='subsistemas_start'),

    url(r'^aspirantes-con-pago-sin-pase-al-examen/$', views.AspirantesConPagoSinProcesoCompletoView.as_view(), name='aspirantes_con_pago_sin_pase_al_examen'),
    url(r'^aspirantes-sin-pago/$', views.AspirantesSinPagoEfectuado.as_view(), name='aspirantes_sin_pago'),

    url(r'^especialidades/$', views.EspecialidadListView.as_view(), name='especialidades_list'),
    url(r'^especialidades/nuevo$', views.EspecialidadCreateView.as_view(), name='especialidades_create'),

    url(r'^aforo/enviar/$', views.EnviarAforo.as_view(), name='aforo_submit'),
    url(r'^aforo/rechazo/$', views.RevisionAforoRechazoView.as_view(), name='aforo_reject'),
    url(r'^oferta/enviar/$', views.EnviarOfertaEducativa.as_view(), name='ofertas_submit'),
    url(r'^oferta/rechazo/$', views.RevisionOfertaEducativaView.as_view(), name='ofertas_reject'),

    url(r'^oferta/nueva/$', views.OfertaEducativaCreateView.as_view(), name='ofertas_create'),
    url(r'^oferta/ajuste/(?P<oferta_id>[\d]+)/$', views.PoblacionEstudiantilView.as_view(), name='ofertas_adjust'),
    url(r'^oferta/ajuste/(?P<oferta_id>[\d]+)/delete/$', views.PoblacionEstudiantilDeleteView.as_view(), name='poblacion_delete'),

    url(r'^planteles/$', views.PlantelListView.as_view(), name='planteles_list'),
    url(r'^planteles/nuevo/$', views.PlantelCreateView.as_view(), name='planteles_create'),
    url(r'^planteles/activar/$', views.ActivatePlantelView.as_view(), name='planteles_activate'),
    url(r'^planteles/desactivar/$', views.DeactivatePlantelView.as_view(), name='planteles_deactivate'),
    url(r'^planteles/editar/(?P<pk>[\d]+)/$', views.PlantelUpdateView.as_view(), name='planteles_edit'),

    url(r'^planteles/(?P<plantel_id>[\d]+)/oferta/$', views.OfertaEducativaListView.as_view(), name='ofertas'),
    url(r'^planteles/(?P<plantel_id>[\d]+)/oferta/eliminar/$', views.OfertaEducativaDeleteView.as_view(), name='ofertas_delete'),
    url(r'^planteles/(?P<plantel_id>[\d]+)/oferta/activar/$', views.ActivateOfertaEducativa.as_view(), name='ofertas_activate'),
    url(r'^planteles/(?P<plantel_id>[\d]+)/oferta/desactivar/$', views.DeactivateOfertaEducativa.as_view(), name='ofertas_deactivate'),
    url(r'^planteles/(?P<plantel_id>[\d]+)/oferta/(?P<oferta_id>[\d]+)/proyeccion$', views.OfertaEducativaProyeccion.as_view(),
        name='ofertas_proyeccion'),

    url(r'^planteles/(?P<plantel_id>[\d]+)/aforo/$', views.AforoListView.as_view(), name='aforos_list'),
    url(r'^planteles/(?P<plantel_id>[\d]+)/aforo/eliminar/$', views.AforoDeleteView.as_view(), name='aforos_delete'),
]

exameneducacionmedia/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from app.accounts.views import LoginRedirectView, LogoutRedirectView
from exameneducacionmedia import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^', include('app.home.urls', namespace='home')),

    url(r'^administracion/', include('app.administracion.urls', namespace='administracion')),
    url(r'^administracion/', include('app.staff.urls', namespace='administracion')),
    url(r'^aspirantes/', include('app.aspirantes.urls', namespace='aspirantes')),
    url(r'^accounts/', include('app.accounts.urls', namespace='accounts')),
    url(r'^planteles/', include('app.planteles.urls', namespace='planteles')),
    url(r'^reportes/', include('app.reportes.urls', namespace='reportes')),
    url(r'^subsistemas/', include('app.subsistemas.urls', namespace='subsistemas')),

    url(r'^mgeo/', include('app.mgeo.urls', namespace='mgeo')),
    url(r'^login/$', LoginRedirectView.as_view(), name='redirect_to_login'),
    url(r'^logout/$', LogoutRedirectView.as_view(), name='redirect_to_logout'),

    url(r'^billy/', include('app.billy.urls', namespace='billy')),

    url(r'^finanzas/', include('app.finanzas.urls', namespace='finanzas')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/subsistemas/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

app/administracion/views/subsistemas.py
# -*- encoding: utf-8 -*
from django.contrib.auth.models import User, Group
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import generic

from app.administracion.forms import SubsistemaModelForm
from app.planteles.models import Subsistema
from general.mixins import LoginRequiredMixin


class SubsistemaListView(generic.ListView):
    model = Subsistema
    template_name = 'subsistemas/list.html'
    context_object_name = 'subsistemas'

    def get_queryset(self):
        return self.model.objects.select_related('responsable').all()


class SubsistemaCreateView(generic.View):
    template_name = 'subsistemas/create.html'

    def get(self, request):
        return render(request, self.template_name, {})

    def post(self, request):
        transaction.set_autocommit(False)
        try:
            subsistema = Subsistema()

            subsistema.referencia = request.POST['referencia']
            subsistema.descripcion = request.POST['descripcion']

            username = request.POST['username']
            password = request.POST['password']
            email = request.POST['email']
            first_name = request.POST['first_name']
            last_name = request.POST['last_name']

            user = User.objects.create_user(username, email, password)
            user.first_name = first_name
            user.last_name = last_name

            user.save()

            subsistema.responsable = user

            subsistema.save()

            user.groups.clear()
            group = Group.objects.get(name='subsistema')
            user.groups.add(group)

            transaction.commit()
            return HttpResponseRedirect(reverse("administracion:subsistemas_list"))
        except Exception as e:
            response = render(request, self.template_name, {'error': e})
            transaction.rollback()
            return response


class SubsistemaUpdateView(generic.UpdateView):
    model = Subsistema
    template_name = 'subsistemas/edit.html'
    context_object_name = 'subsistema'
    form_class = SubsistemaModelForm

app/planteles/views/oferta.py
# -*- encoding: utf-8 -*
from django.views import generic


class OfertaView(generic.View):
    pass

app/subsistemas/views.py
from django.shortcuts import render

# Create your views here.

app/subsistemas/views/aforos.py
# -*- encoding: utf-8 -*
from django.contrib import messages
from django.db import transaction
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.urls import reverse
from django.views import generic

from app.planteles.models import Aula, AulaPlantel, Plantel
from app.subsistemas.forms import AulaPlantelForm
from general.mixins import LoginRequiredMixin, NeedsSubsistemaGroupAccessMixin


class AforoListView(LoginRequiredMixin, NeedsSubsistemaGroupAccessMixin, generic.ListView):
    model = AulaPlantel
    template_name = "aforos/list.html"
    context_object_name = "aforos"

    def get_queryset(self):
        queryset = self.model.objects.select_related('aula', 'plantel').filter(plantel__id=self.kwargs['plantel_id'])
        return queryset

    def get_context_data(self, **kwargs):
        context = super(AforoListView, self).get_context_data(**kwargs)
        context.update({
            'plantel': Plantel.objects.select_related('subsistema').get(pk=self.kwargs['plantel_id']),
            'form': AulaPlantelForm(auto_id='%s')
        })
        return context

    def post(self, request, plantel_id):
        plantel = Plantel.objects.get(pk=plantel_id)
        transaction.set_autocommit(False)
        form = AulaPlantelForm(request.POST, auto_id='%s')
        try:
            if form.is_valid():
                self.tiene_revision_aforo_pendiente(request.user)
                aula = AulaPlantel()
                aula.referencia = form.cleaned_data['referencia']
                aula.capacidad = form.cleaned_data['capacidad']
                aula.plantel = plantel
                aula.save()

                transaction.commit()
                return HttpResponseRedirect(reverse('subsistemas:aforos_list', kwargs={'plantel_id': plantel.id}))
        except Exception as e:
            transaction.rollback()
            messages.info(request, e.message)
            return HttpResponseRedirect(reverse('subsistemas:aforos_list', kwargs={'plantel_id': plantel.id}))


class AforoCreateView(generic.ListView):
    pass


class AforoDeleteView(LoginRequiredMixin, NeedsSubsistemaGroupAccessMixin, generic.DeleteView):
    def post(self, request, plantel_id):
        transaction.set_autocommit(False)
        try:
            subsistema = self.subsistema_asignado(request.user)
            self.tiene_revision_aforo_pendiente(request.user)
            plantel = Plantel.objects.get(pk=plantel_id)
            aula = Aula.objects.get(pk=request.POST['aula_id'])

            if plantel.subsistema != subsistema:
                raise Exception('No tiene los permisos para hacer este movimiento')

            aula_plantel = AulaPlantel.objects.get(plantel=plantel, aula=aula)
            aula_plantel.delete()

            if not AulaPlantel.objects.filter(aula=aula).exists():
                aula.delete()
            transaction.commit()
            return JsonResponse({'is_valid': True}, safe=False)
        except:
            transaction.rollback()
            raise

app/subsistemas/views/aspirantes.py
# -*- encoding: utf-8 -*
from django.shortcuts import render
from django.views import generic

from general.mixins import LoginRequiredMixin, GroupRequiredMixin, SubsistemaUtils


class AspirantesConPagoSinProcesoCompletoView(LoginRequiredMixin, GroupRequiredMixin, SubsistemaUtils, generic.View):
    group_required = 'subsistema'
    template_name = 'aspirantes/lista_aspirantes_con_pago_sin_pase_al_examen.html'

    def get(self, request):
        subsistema = self.subsistema_asignado(request.user)
        context = {
            'aspirantes': subsistema.list_of_aspirantes_con_pago_sin_proceso_completo()
        }
        return render(request, self.template_name, context)


class AspirantesSinPagoEfectuado(LoginRequiredMixin, GroupRequiredMixin, SubsistemaUtils, generic.View):
    group_required = 'subsistema'
    template_name = 'aspirantes/lista_aspirantes_sin_pago.html'

    def get(self, request):
        subsistema = self.subsistema_asignado(request.user)
        context = {
            'aspirantes': subsistema.list_of_aspirantes_sin_pago_efectuado()
        }
        return render(request, self.template_name, context)

app/subsistemas/views/especialidades.py
# -*- encoding: utf-8 -*
import six
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.views import generic

from app.planteles.models import Especialidad, Plantel
from app.subsistemas.forms import OfertaEducativaModelForm
from general.mixins import LoginRequiredMixin, NeedsSubsistemaGroupAccessMixin, AsegurarEtapaMixin


class EspecialidadListView(LoginRequiredMixin, NeedsSubsistemaGroupAccessMixin, generic.ListView):
    model = Especialidad
    template_name = "especialidades/list.html"
    context_object_name = "especialidades"
    subsistema = None

    def get_queryset(self):
        subsistema = self.subsistema_asignado(self.request.user)
        return self.model.objects.filter(subsistema=subsistema)

    def get_context_data(self, **kwargs):
        context = super(EspecialidadListView, self).get_context_data(**kwargs)
        subsistema = self.subsistema_asignado(self.request.user)
        oferta_form = OfertaEducativaModelForm(auto_id='%s', subsistema=subsistema)
        context.update({
            'subsistema':  self.subsistema,
            'oferta_form': oferta_form
        })
        return context


class EspecialidadCreateView(LoginRequiredMixin, NeedsSubsistemaGroupAccessMixin, AsegurarEtapaMixin, generic.View):
    asegurar_etapa_de = "OFERTA"
    subsistema = None

    def dispatch(self, request, *args, **kwargs):
        self.subsistema = self.subsistema_asignado(request.user)
        return super(EspecialidadCreateView, self).dispatch(request, *args, **kwargs)

    def post(self, request):
        referencia = request.POST.get('referencia')
        descripcion = request.POST.get('descripcion')

        try:
            if not Especialidad.objects.filter(referencia=referencia, subsistema=self.subsistema).exists():
                especialidad = Especialidad()
                especialidad.referencia = referencia
                especialidad.descripcion = descripcion
                especialidad.subsistema = self.subsistema
                especialidad.save()
        except Exception as e:
            messages.add_message(request, messages.INFO, e.message)

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

app/subsistemas/templates/ofertas/ajuste_oferta.html
{% extends 'base_subsistemas.html' %}

{% load staticfiles %}

{% block extra_head %}
{% endblock %}

{% block page_header %}
	{{ subsistema }}
{% endblock %}

{% block optional_description %}
	<small>Grupos</small>
{% endblock %}

{% block html %}
	<div class="content">
		<div class="row">
			<div class="col-md-12">
				<div class="box">
					<div class="box-header with-border">
						<h3 class="box-title">{{ oferta_educativa }}</h3>
						<div class="box-tools pull-right">
							<a href="{% url 'subsistemas:ofertas' plantel.pk %}" class="btn btn-link pull-right"><i class="ion ion-home"></i> Regresar</a>

						</div>
					</div><!-- /.box-header -->
					<div class="box-body no-padding">
						<table class="table table-hover table-bordered">
							<thead>

								<tr>
									<th class="text-right">Grupo</th>
									<th class="text-right">Alumnos por grupo</th>
									<th class="text-right">Repetidores</th>
									<th class="text-right">Total nuevo ingreso</th>
									<th class="text-right">Total de alumnos</th>
									<th>Opciones</th>
								</tr>
								<tr>
									<form action="{% url 'subsistemas:ofertas_adjust' oferta_educativa.pk %}" method="post">
										{% csrf_token %}
										{{ form.oferta_educativa }}
										{{ form.semestre }}
										<th>{{ form.grupos }}</th>
										<th>{{ form.alumnos }}</th>
										<th>{{ form.reprobados }}</th>
										<th><input type="text" id="total_nuevo_ingreso" class="form-control text-right" placeholder="Nuevo ingreso" readonly></th>
										<th><input type="text" id="total" class="form-control text-right" placeholder="Total" readonly></th>
										<th>
											<button class="btn btn-primary">Guardar</button>
										</th>
									</form>
								</tr>
							</thead>
							<tbody>
								{% for grupo in grupos %}
									<tr>
										<td class="text-right">{{ grupo.grupos }}</td>
										<td class="text-right">{{ grupo.alumnos }}</td>
										<td class="text-right">{{ grupo.reprobados }}</td>
										<td class="text-right">{{ grupo.total_nuevo_ingreso }}</td>
										<td class="text-right">{{ grupo.total }}</td>
										<td>
											<form action="{% url 'subsistemas:poblacion_delete' grupo.id %}" method="post">
												{% csrf_token %}
												<input type="hidden" name="grupo_id" value="{{ grupo.pk }}">
												<button class="btn btn-danger" data-button="delete" type="button">Eliminar</button>
											</form>
										</td>
									</tr>
								{% empty %}
									<tr>
										<td colspan="6">Sin resultados</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
					</div><!-- /.box-body -->
					<div class="box-footer">
					</div><!-- box-footer -->
				</div><!-- /.box -->
			</div>
		</div>
	</div>
{% endblock %}

{% block extra_scripts %}
	<script type="text/javascript" src="{% static 'bower/bootbox.js/bootbox.js' %}"></script>
	<script type="text/javascript">
		(function () {
			var $btnDeleteGrupo  = $('[data-button="delete"]'),
				$txtTotal        = $('#total'),
				$txtAlumnos      = $('#alumnos'),
				$txtGrupos       = $('#grupos'),
				$txtNuevoIngreso = $('#total_nuevo_ingreso'),
				$txtReprobados   = $('#reprobados');

			$btnDeleteGrupo.on("click", onClickBtnGrupo);
			$txtAlumnos.on("keyup", function () {
				$txtTotal.val($(this).val() * $txtGrupos.val());
			});

			$txtGrupos.on("keyup", function () {
				$txtTotal.val($(this).val() * $txtAlumnos.val());
			});

			$txtReprobados.on("keyup", function () {
				$txtNuevoIngreso.val($txtAlumnos.val() - $(this).val());
			});

			function onClickBtnGrupo() {
				var that = this;
				bootbox.confirm({
					message: "¿Desea eliminar el grupo, esta acción no se puede deshacer?",
					buttons: {
						confirm: {
							label: 'Si',
							className: 'btn-success'
						},
						cancel: {
							label: 'No',
							className: 'btn-danger'
						}
					},
					callback: function (result) {
						if (result) {
							var $form = $(that).closest('form');
							$form.submit();
						} else {
							console.log("no")
						}
					}
				});
			}
		}());
	</script>
{% endblock %}

app/subsistemas/templates/ofertas/create.html
{% extends 'base_subsistemas.html' %}

{% block extra_head %}

{% endblock %}

{% block page_header %}
	{{ plantel }}
{% endblock %}

{% block optional_description %}
<small>Nueva especialidad</small>
{% endblock %}

{% block html %}
	<div class="content">
		<div class="row">
			<div class="col-md-7">
				<div class="box box-warning">
					<div class="box-header with-border">
						<h3 class="box-title" data-widget="collapse" style="cursor: pointer">+ Agregar especialidad</h3>
						<!-- /.box-tools -->
					</div>
					<!-- /.box-header -->
					<div class="box-body">
						{% if form.errors %}
							<div class="alert alert-danger">
								<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
								<strong>Error</strong> Los campos marcados en rojo son requeridos
							</div>
						{% endif %}
						<form action="{% url 'subsistemas:ofertas_create' plantel.pk %}" method="post" id="oferta-educativa-form">
							{% csrf_token %}
							{{ form.as_p }}
							{% comment %}<div class="row">
								<div class="col-md-4">
									<label>Grupos</label>
									<input type="number" min="1" name="grupos" class="form-control text-right">
								</div>
								<div class="col-md-4">
									<label>Alumnos</label>
									<input type="number" min="1" name="alumnos" class="form-control text-right">
								</div>
								<div class="col-md-4">
									<label>Grupos</label>
									<input type="text" min="1" readonly id="total" class="form-control text-right">
								</div>
							</div>{% endcomment %}
						</form>
					</div>
					<!-- /.box-body -->
					<div class="box-footer">
						<button class="btn btn-primary pull-right" type="submit" form="oferta-educativa-form">Guardar</button>
					</div>
					<!-- /.box-footer -->
				</div>
			</div>
		</div>
	</div>
{% endblock %}

{% block extra_scripts %}
{% endblock %}

app/subsistemas/templates/ofertas/especialidades_con_proyeccion_snippet.html
<table class="table table-hover table-bordered">
	<thead>
		<tr>
			<th colspan="1" style="text-align: center" width="20%">Especialidad</th>
			<th colspan="3" style="text-align: center" width="15%">Matricula esperada</th>
		</tr>
		<tr style="color:#999999">
			<td>Nombre</td>
			<td class="text-right">Grupos</td>
			<td class="text-right">Alumnos</td>
			<td class="text-right">Total</td>
		</tr>
	</thead>
	<tbody>
		{% for oferta in proyeccion %}
			<tr>
				<td>{{ oferta.oferta_educativa.especialidad.referencia }}</td>
				<td class="text-right">{{ oferta.grupos }}</td>
				<td class="text-right">{{ oferta.alumnos }}</td>
				<td class="text-right">{{ oferta.total }}</td>
			</tr>
		{% empty %}
			<tr><td colspan="9">Sin resultados</td></tr>
		{% endfor %}
	</tbody>
</table>

app/subsistemas/templates/ofertas/especialidades_snippet.html
<table class="table table-hover">
	<thead>
		<tr>
			<th width="1%" rowspan="2">No.</th>
			<th width="2%" rowspan="2"></th>
			<th width="15%" rowspan="2">Especialidad</th>
			<th width="5%" rowspan="2">Estado</th>
			<th width="5%" rowspan="2">Activar/Desactivar</th>
			<th colspan="3" class="text-center">Proyeccion</th>
		</tr>
		<tr>
			<th width="3%" class="text-right">Grupos</th>
			<th width="10%" class="text-right">Alumnos por grupo</th>
			<th width="10%" class="text-right">Total de alumnos</th>
		</tr>
	</thead>

	<tbody>
		{% for oferta in oferta_educativa %}
			<tr>
				<td>{{ forloop.counter }}</td>
				<td>
					{% if oferta.activa %}
						<div class="dropdown">
							<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
								Opciones
								<span class="caret"></span>
							</button>
							<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
								<li role="presentation">
									<a href="#!"
									   data-button="open-modal-proyeccion-form"
									   data-toggle="modal"
									   data-target="#agregar-proyeccion-form"
									   data-url="{% url 'subsistemas:ofertas_proyeccion' plantel.pk oferta.pk %}"
									   title="La proyección es el estimado de alumnos que el plantel va a recibir por especialidad">Editar proyección</a>
								</li>
								<li role="presentation">
									<a href="{% url 'subsistemas:ofertas_adjust' oferta.pk %}"
									   data-toggle="tooltip" {% if not is_ajuste_oferta %}disabled{% endif %}
									   title="El ajuste de oferta te servirá para agregar los grupos que reales que va a recbir el plantel">Ajustar
																																			oferta</a>
								</li>
							</ul>
						</div>
					{% endif %}
				</td>
				<td>{{ oferta.especialidad.referencia }}</td>
				<td>{{ oferta.status }}</td>
				<td>
					{% if oferta.activa %}
						<form action="{% url 'subsistemas:ofertas_deactivate' plantel_id=plantel.id %}" method="post">
							{% csrf_token %}
							<input type="hidden" name="especialidad_id" value="{{ oferta.especialidad.id }}">
							<button type="button" class="btn btn-link" data-button="deactivate" data-toggle="tooltip"
									title="Al desactivar una especialidad esta no estará disponible para ser seleccionada por el alumno.">Desactivar
							</button>
						</form>
					{% else %}
						<form action="{% url 'subsistemas:ofertas_activate' plantel_id=plantel.id %}" method="post">
							{% csrf_token %}
							<input type="hidden" name="especialidad_id" value="{{ oferta.especialidad.id }}">
							<button type="button" class="btn btn-link" data-button="activate" data-toggle="tooltip"
									title="Al activar una especialidad esta estará disponible para ser seleccionada por el alumno.">Activar
							</button>
						</form>
					{% endif %}
				</td>
				<td class="text-right">{{ oferta.grupos }}</td>
				<td class="text-right">{{ oferta.alumnos }}</td>
				<td class="text-right">{{ oferta.total_proyeccion }}</td>


			</tr>
		{% empty %}
			<tr>
				<td colspan="4">Sin resultados</td>
			</tr>
		{% endfor %}
	</tbody>
</table>

app/subsistemas/templates/ofertas/list.html
{% extends 'base_subsistemas.html' %}

{% load staticfiles %}

{% block extra_head %}
	<link rel="stylesheet" href="{% static "css/misc.css" %}">
{% endblock %}

{% block page_header %}
	{{ plantel.subsistema }} - {{ plantel }}
{% endblock %}

{% block optional_description %}
	<small>OFERTA EDUCATIVA</small>
{% endblock %}

{% block html %}
	<section class="content">
		{% if messages %}
			<div class="row">
				<div class="col-md-12">
					<div class="alert alert-warning">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<ul class="messages">
							{% for message in messages %}
								<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
							{% endfor %}
						</ul>
					</div>
				</div>
			</div>

		{% endif %}

		<div class="row">
			<div class="col-md-12">

				<div class="box">
					<div class="box-header with-border">
						<h3 class="box-title">Oferta educativa</h3>
						<div class="box-tools">
							<button class="btn btn-link" data-toggle="modal" data-target="#add-oferta-modal">
								<i class="fa fa-plus-circle"></i> Oferta educativa
							</button>
							<a href="{% url 'subsistemas:subsistemas_start' %}" class="btn btn-link"><i class="ion ion-home"></i> Regresar</a>
						</div>
					</div><!-- /.box-header -->
					<div class="box-body table-responsive no-padding">
						{% include 'ofertas/especialidades_snippet.html' %}
					</div><!-- /.box-body -->
				</div><!-- /.box -->
			</div>
		</div>
	</section>

	<div class="modal fade" id="agregar-proyeccion-form">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title">Proyección</h4>
				</div>
				<div class="modal-body">
					<form action="" method="post" id="proyeccion-form">
						{% csrf_token %}
						<div class="row">
							<div class="col-md-4">
								<div class="form-group">
									<label class="control-label">Grupos</label>
									<input type="number" class="form-control text-right" data-field="grupos_proyeccion_1" name="grupos" required min="1">
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label class="control-label">Alumnos por grupo</label>
									<input type="number" class="form-control text-right" data-field="alumnos_proyeccion_1" name="alumnos" required min="1">
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label class="control-label">Total de alumnos</label>
									<input type="text" class="form-control text-right" data-field="total_proyeccion_1" required readonly>
								</div>
							</div>
						</div>
					</form>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
					<button type="submit" class="btn btn-primary" form="proyeccion-form">Guardar</button>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
	{% include "especialidades/partials/add_oferta_modal_snippet.html" with oferta_form=form %}

{% endblock %}

{% block extra_scripts %}
	<script type="text/javascript" src="{% static "bower/bootbox.js/bootbox.js" %}"></script>
	<script type="text/javascript" src="{% static "ofertas/js/list.js" %}"></script>
	<script type="text/javascript" src="{% static 'especialidades/add_oferta_modal.js' %}"></script>
{% endblock %}