app/mgeo/urls.py
# -*- encoding: utf-8 -*
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^localidades/$', views.localidades, name="localidades"),
    url(r'^localidades/(?P<municipio_id>[0-9]+)/$', views.localidades, name="localidades")
]

app/planteles/urls.py
# -*- encoding: utf-8 -*
from django.conf.urls import url

from app.planteles import views


# **************************************
#
#   url: /plantel/
#   namespace: planteles
#
# **************************************

urlpatterns = [
    url(r'^$', views.PLantelHomeView.as_view(), name='home'),
    url(r'^aspirantes/sin-pago-efectuado/$', views.AspirantesSinPagoTemplateView.as_view(), name='aspirante_sin_pago_efecutado'),
    url(r'^(?P<plantel_id>[\d]+)/oferta/$', views.OfertaView.as_view(), name='oferta'),
]

app/subsistemas/urls.py
# -*- encoding: utf-8 -*
from django.conf.urls import url

from app.subsistemas import views

# **************************************
#
#   url: /subsistemas/
#   namespace: subsistemas
#
# **************************************

urlpatterns = [
    url(r'^$', views.StartTemplateView.as_view(), name='subsistemas_start'),

    url(r'^aspirantes-con-pago-sin-pase-al-examen/$', views.AspirantesConPagoSinProcesoCompletoView.as_view(), name='aspirantes_con_pago_sin_pase_al_examen'),
    url(r'^aspirantes-sin-pago/$', views.AspirantesSinPagoEfectuado.as_view(), name='aspirantes_sin_pago'),

    url(r'^especialidades/$', views.EspecialidadListView.as_view(), name='especialidades_list'),
    url(r'^especialidades/nuevo$', views.EspecialidadCreateView.as_view(), name='especialidades_create'),

    url(r'^aforo/enviar/$', views.EnviarAforo.as_view(), name='aforo_submit'),
    url(r'^aforo/rechazo/$', views.RevisionAforoRechazoView.as_view(), name='aforo_reject'),
    url(r'^oferta/enviar/$', views.EnviarOfertaEducativa.as_view(), name='ofertas_submit'),
    url(r'^oferta/rechazo/$', views.RevisionOfertaEducativaView.as_view(), name='ofertas_reject'),

    url(r'^oferta/nueva/$', views.OfertaEducativaCreateView.as_view(), name='ofertas_create'),
    url(r'^oferta/ajuste/(?P<oferta_id>[\d]+)/$', views.PoblacionEstudiantilView.as_view(), name='ofertas_adjust'),
    url(r'^oferta/ajuste/(?P<oferta_id>[\d]+)/delete/$', views.PoblacionEstudiantilDeleteView.as_view(), name='poblacion_delete'),

    url(r'^planteles/$', views.PlantelListView.as_view(), name='planteles_list'),
    url(r'^planteles/nuevo/$', views.PlantelCreateView.as_view(), name='planteles_create'),
    url(r'^planteles/activar/$', views.ActivatePlantelView.as_view(), name='planteles_activate'),
    url(r'^planteles/desactivar/$', views.DeactivatePlantelView.as_view(), name='planteles_deactivate'),
    url(r'^planteles/editar/(?P<pk>[\d]+)/$', views.PlantelUpdateView.as_view(), name='planteles_edit'),

    url(r'^planteles/(?P<plantel_id>[\d]+)/oferta/$', views.OfertaEducativaListView.as_view(), name='ofertas'),
    url(r'^planteles/(?P<plantel_id>[\d]+)/oferta/eliminar/$', views.OfertaEducativaDeleteView.as_view(), name='ofertas_delete'),
    url(r'^planteles/(?P<plantel_id>[\d]+)/oferta/activar/$', views.ActivateOfertaEducativa.as_view(), name='ofertas_activate'),
    url(r'^planteles/(?P<plantel_id>[\d]+)/oferta/desactivar/$', views.DeactivateOfertaEducativa.as_view(), name='ofertas_deactivate'),
    url(r'^planteles/(?P<plantel_id>[\d]+)/oferta/(?P<oferta_id>[\d]+)/proyeccion$', views.OfertaEducativaProyeccion.as_view(),
        name='ofertas_proyeccion'),

    url(r'^planteles/(?P<plantel_id>[\d]+)/aforo/$', views.AforoListView.as_view(), name='aforos_list'),
    url(r'^planteles/(?P<plantel_id>[\d]+)/aforo/eliminar/$', views.AforoDeleteView.as_view(), name='aforos_delete'),
]

exameneducacionmedia/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from app.accounts.views import LoginRedirectView, LogoutRedirectView
from exameneducacionmedia import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^', include('app.home.urls', namespace='home')),

    url(r'^administracion/', include('app.administracion.urls', namespace='administracion')),
    url(r'^administracion/', include('app.staff.urls', namespace='administracion')),
    url(r'^aspirantes/', include('app.aspirantes.urls', namespace='aspirantes')),
    url(r'^accounts/', include('app.accounts.urls', namespace='accounts')),
    url(r'^planteles/', include('app.planteles.urls', namespace='planteles')),
    url(r'^reportes/', include('app.reportes.urls', namespace='reportes')),
    url(r'^subsistemas/', include('app.subsistemas.urls', namespace='subsistemas')),

    url(r'^mgeo/', include('app.mgeo.urls', namespace='mgeo')),
    url(r'^login/$', LoginRedirectView.as_view(), name='redirect_to_login'),
    url(r'^logout/$', LogoutRedirectView.as_view(), name='redirect_to_logout'),

    url(r'^billy/', include('app.billy.urls', namespace='billy')),

    url(r'^finanzas/', include('app.finanzas.urls', namespace='finanzas')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/subsistemas/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

app/planteles/forms.py
# -*- encoding: utf-8 -*

app/administracion/views/planteles.py
# -*- encoding: utf-8 -*-

import decimal

from django.contrib import messages
from django.contrib.auth.models import Group, User
from django.db import transaction
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import generic

from app.billy.models import SalarioMinimo, Concepto
from app.planteles.models import Plantel, Subsistema
from general.mixins import LoginRequiredMixin, NeedsDepartamentoGroupAccessMixin, GroupRequiredMixin


class PlantelListView(LoginRequiredMixin, NeedsDepartamentoGroupAccessMixin, generic.ListView):
    model = Plantel
    template_name = "planteles/list.html"
    context_object_name = 'planteles'

    def get_queryset(self):
        queryset = self.model.objects.select_related('responsable', 'subsistema')
        if 'subsistema' in self.request.GET:
            return queryset.filter(subsistema__id=self.request.GET.get('subsistema'))

        if 'search' in self.request.GET:
            term = self.request.GET['search']
            return queryset.filter(Q(referencia__icontains=term) | Q(cct__icontains=term))

        return queryset

    def get_context_data(self, **kwargs):
        context = super(PlantelListView, self).get_context_data(**kwargs)
        salario_minimo = SalarioMinimo.objects.get(activo=True)
        concepto = Concepto.objects.get(clave='026')
        monto = concepto.salarios_minimos * salario_minimo.monto
        total = str(monto.quantize(decimal.Decimal('0'), rounding=decimal.ROUND_HALF_UP)),
        context.update({
            'total': total    [0],
            'concepto':       concepto,
            'subsistemas':    Subsistema.objects.all(),
            'salario_minimo': salario_minimo,
        })
        return context


class PlantelUpdateView(LoginRequiredMixin, NeedsDepartamentoGroupAccessMixin, generic.View):
    def post(self, request, pk):
        try:
            plantel = Plantel.objects.get(pk=pk)
            plantel.descuento = request.POST.get('precio')
            plantel.save()
            data = {'is_valid': True}
        except Exception as e:
            data = {'is_valid': False, 'message': e.message}

        return JsonResponse(data, safe=False)


class PlantelChangeResponsible(LoginRequiredMixin, GroupRequiredMixin, generic.View):
    group_required = 'departamento'
    template_name = 'planteles/change_responsible.html'

    def get(self, request, pk):
        context = {
            'group':      Group.objects.values('pk').get(name__exact='plantel'),
            'plantel_id': pk,
        }
        return render(request, self.template_name, context)

    def post(self, request, pk):
        plantel = Plantel.objects.get(pk=pk)
        transaction.set_autocommit(False)
        try:
            first_name = request.POST.get('first_name')
            last_name = request.POST.get('last_name')
            email = request.POST.get('email')
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = User.objects.create_user(username, email, password)
            user.first_name = first_name
            user.last_name = last_name

            user.save()

            plantel.responsable = user

            plantel.save()

            user.groups.clear()
            group = Group.objects.get(name='plantel')
            user.groups.add(group)
            messages.success(request, "El responsable del plantel se cambió correctamente")
            transaction.commit()
        except Exception as e:
            transaction.rollback()
            messages.error(request, e.message)
            return redirect(request.META.get('HTTP_REFERER'))

        return redirect(reverse('administracion:plantel_list'))

app/administracion/views/subsistemas.py
# -*- encoding: utf-8 -*
from django.contrib.auth.models import User, Group
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import generic

from app.administracion.forms import SubsistemaModelForm
from app.planteles.models import Subsistema
from general.mixins import LoginRequiredMixin


class SubsistemaListView(generic.ListView):
    model = Subsistema
    template_name = 'subsistemas/list.html'
    context_object_name = 'subsistemas'

    def get_queryset(self):
        return self.model.objects.select_related('responsable').all()


class SubsistemaCreateView(generic.View):
    template_name = 'subsistemas/create.html'

    def get(self, request):
        return render(request, self.template_name, {})

    def post(self, request):
        transaction.set_autocommit(False)
        try:
            subsistema = Subsistema()

            subsistema.referencia = request.POST['referencia']
            subsistema.descripcion = request.POST['descripcion']

            username = request.POST['username']
            password = request.POST['password']
            email = request.POST['email']
            first_name = request.POST['first_name']
            last_name = request.POST['last_name']

            user = User.objects.create_user(username, email, password)
            user.first_name = first_name
            user.last_name = last_name

            user.save()

            subsistema.responsable = user

            subsistema.save()

            user.groups.clear()
            group = Group.objects.get(name='subsistema')
            user.groups.add(group)

            transaction.commit()
            return HttpResponseRedirect(reverse("administracion:subsistemas_list"))
        except Exception as e:
            response = render(request, self.template_name, {'error': e})
            transaction.rollback()
            return response


class SubsistemaUpdateView(generic.UpdateView):
    model = Subsistema
    template_name = 'subsistemas/edit.html'
    context_object_name = 'subsistema'
    form_class = SubsistemaModelForm

app/planteles/views/aspirantes.py
# -*- encoding: utf-8 -*
from django.views import generic

from app.planteles.utils import PlantelUtils


class AspirantesSinPagoTemplateView(PlantelUtils, generic.TemplateView):
    template_name = 'aspirantes/sin_pago_efectuado.html'

    def get_context_data(self, **kwargs):
        context = super(AspirantesSinPagoTemplateView, self).get_context_data(**kwargs)
        plantel = self.plantel
        aspirantes_sin_pago = plantel.aspirantes_sin_pago_completado()
        context.update({
            'plantel':                   plantel,
            'aspirantes_sin_pago':       aspirantes_sin_pago,
            'aspirantes_sin_pago_count': len(list(aspirantes_sin_pago))
        })
        return context

app/planteles/views/home.py
# -*- encoding: utf-8 -*
from django.views import generic

from app.planteles.models import SedeAlterna
from app.planteles.utils import PlantelUtils


class PLantelHomeView(PlantelUtils, generic.TemplateView):
    template_name = 'home/home.html'

    def get_context_data(self, **kwargs):
        context = super(PLantelHomeView, self).get_context_data(**kwargs)
        plantel = self.plantel

        capacidad_total = 0 if plantel.capacidad_total(incluir_sedes_alternas=False) is None else plantel.capacidad_total(incluir_sedes_alternas=False)
        total_aulas = plantel.total_aulas(incluir_sedes_alternas=False)
        capacidad_ocupada = 0 if plantel.capacidad_ocupada(incluir_sedes_alternas=False) is None else plantel.capacidad_ocupada(incluir_sedes_alternas=False)
        oferta_eduacativa_related = plantel.oferta_eduacativa_related.all()
        demanda = plantel.demanda

        try:
            porcentaje_ocupado = int((float(100) / capacidad_total) * capacidad_ocupada)
        except:
            porcentaje_ocupado = 0

        plantel.totales = {
            'capacidad':          capacidad_total,
            'aulas':              total_aulas,
            'capacidad_ocupada':  capacidad_ocupada,
            'oferta_educativa':   oferta_eduacativa_related,
            'demanda':            demanda,
            'porcentaje_ocupado': porcentaje_ocupado
        }

        if SedeAlterna.objects.filter(plantel=plantel).exists():
            plantel.sedes_alternas = SedeAlterna.objects.filter(plantel=plantel).all()
            for sede_alterna in plantel.sedes_alternas:
                capacidad_total = sede_alterna.capacidad_total()
                aulas = sede_alterna.total_aulas()
                capacidad_ocupada = sede_alterna.capacidad_ocupada_1(plantel.id)

                sede_alterna.totales = {
                    'capacidad':          capacidad_total,
                    'aulas':              aulas,
                    'capacidad_ocupada':  capacidad_ocupada,
                    'porcentaje_ocupado': int((float(100) / capacidad_total) * capacidad_ocupada)
                }

        aspirantes_sin_pago = plantel.aspirantes_sin_pago_completado()
        aspirantes_con_proceso_completo = plantel.aspirantes_con_proceso_completo()
        context.update({
            'plantel':             plantel,
            'aspirantes_sin_pago_count': len(list(aspirantes_sin_pago)),
            'aspirantes_con_proceso_completo': len(list(aspirantes_con_proceso_completo))
        })
        return context

app/planteles/views/oferta.py
# -*- encoding: utf-8 -*
from django.views import generic


class OfertaView(generic.View):
    pass

app/subsistemas/views.py
from django.shortcuts import render

# Create your views here.

app/subsistemas/views/aspirantes.py
# -*- encoding: utf-8 -*
from django.shortcuts import render
from django.views import generic

from general.mixins import LoginRequiredMixin, GroupRequiredMixin, SubsistemaUtils


class AspirantesConPagoSinProcesoCompletoView(LoginRequiredMixin, GroupRequiredMixin, SubsistemaUtils, generic.View):
    group_required = 'subsistema'
    template_name = 'aspirantes/lista_aspirantes_con_pago_sin_pase_al_examen.html'

    def get(self, request):
        subsistema = self.subsistema_asignado(request.user)
        context = {
            'aspirantes': subsistema.list_of_aspirantes_con_pago_sin_proceso_completo()
        }
        return render(request, self.template_name, context)


class AspirantesSinPagoEfectuado(LoginRequiredMixin, GroupRequiredMixin, SubsistemaUtils, generic.View):
    group_required = 'subsistema'
    template_name = 'aspirantes/lista_aspirantes_sin_pago.html'

    def get(self, request):
        subsistema = self.subsistema_asignado(request.user)
        context = {
            'aspirantes': subsistema.list_of_aspirantes_sin_pago_efectuado()
        }
        return render(request, self.template_name, context)

app/subsistemas/templates/planteles/create.html
{% extends 'base_subsistemas.html' %}

{% load staticfiles %}

{% block extra_head %}
	<link rel="stylesheet" href="{% static "css/misc.css" %}">
	<link rel="stylesheet" href="{% static "bower/AdminLTE/plugins/select2/select2.min.css" %}">
{% endblock %}

{% block page_header %}Plantel{% endblock %}
{% block optional_description %}
	<small>Nueva</small>{% endblock %}

{% block html %}
	<section class="content">
		{% if form.errors %}
			<div class="alert alert-danger">
				<button type="button" class="close" data-dismiss="alert"
						aria-hidden="true">&times;</button>
				<strong>Error</strong> Los campos marcados en rojo son requeridos
			</div>
		{% endif %}
		<form action="{% url 'subsistemas:planteles_create' %}" class="form-horizontal" id="subsistema-form" method="post">
			{% include "planteles/form.html" %}
		</form>

		<div class="row">
			<div class="col-md-8">
				<div class="toolbar">
					<a href="{% url 'subsistemas:subsistemas_start' %}" class="btn btn-default pull-right">Cancelar</a>
					<button type="submit" class="btn btn-primary" form="subsistema-form">Guardar</button>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-8"></div>
		</div>
	</section>
{% endblock %}

{% block extra_scripts %}
	<script type="text/javascript" src="{% static "bower/AdminLTE/plugins/select2/select2.full.min.js" %}"></script>
	<script type="text/javascript" src="{% static "planteles/js/create.js" %}"></script>
{% endblock %}

app/subsistemas/templates/planteles/edit.html
{% extends 'base_subsistemas.html' %}

{% load staticfiles %}

{% block extra_head %}
	<link rel="stylesheet" href="{% static "css/misc.css" %}">
	<link rel="stylesheet" href="{% static "bower/AdminLTE/plugins/select2/select2.min.css" %}">
{% endblock %}

{% block page_header %}Plantel{% endblock %}
{% block optional_description %}
	<small>Editar</small>{% endblock %}

{% block html %}
	<section class="content">
	{% if form.errors %}
							<div class="alert alert-danger">
								<button type="button" class="close" data-dismiss="alert"
								        aria-hidden="true">&times;</button>
								<strong>Error</strong> Los campos marcados en rojo son requeridos
							</div>
						{% endif %}
	<form action="{% url 'subsistemas:planteles_edit' plantel.pk %}" class="form-horizontal" id="subsistema-form" method="post">
		{% include "planteles/formUpdate.html" %}
	</form>

	<div class="row">
			<div class="col-md-8">
				<div class="toolbar">
					<a href="{% url 'subsistemas:subsistemas_start' %}" class="btn btn-default pull-right">Cancelar</a>
					<button type="submit" class="btn btn-primary" form="subsistema-form">Editar</button>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-8"></div>
		</div>
	</section>
{% endblock %}

{% block extra_scripts %}
	<script type="text/javascript" src="{% static "bower/AdminLTE/plugins/select2/select2.full.min.js" %}"></script>
	<script type="text/javascript" src="{% static "planteles/js/create.js" %}"></script>
{% endblock %}

app/subsistemas/templates/planteles/form.html
{% csrf_token %}

<div class="row">
	<div class="col-md-8">
		<div class="box">
			<div class="box-header with-border">
				<h3 class="box-title">Datos del plantel</h3>
			</div><!-- /.box-header -->
			<div class="box-body">
			<input type="hidden" id="get-json-localidades" data-url="{% url 'mgeo:localidades' %}">
				<div class="form-group">
					<label {% if form.referencia.errors %}style="color:red"{% endif %}
					       for="{{ form.referencia.auto_id }}"
					       class="col-md-3 control-label">{{ form.referencia.label }}</label>
					<div class="col-md-9">
						{{ form.referencia }}
					</div>
				</div>
				<div class="form-group">
					<label {% if form.cct.errors %}style="color:red"{% endif %} for="{{ form.cct.auto_id }}"
					       class="col-md-3 control-label">{{ form.cct.label }}</label>
					<div class="col-md-9">
						{{ form.cct }}
					</div>
				</div>

            <div class="form-group">
					<label {% if form.telefono.errors %}style="color:red"{% endif %} for="{{ form.telefono.auto_id }}"
					       class="col-md-3 control-label">{{ form.telefono.label }}</label>
					<div class="col-md-9">
						{{ form.telefono }}
					</div>
				</div>

            <div class="form-group">
					<label {% if form.pagina_web.errors %}style="color:red"{% endif %} for="{{ form.pagina_web.auto_id }}"
					       class="col-md-3 control-label">{{ form.pagina_web.label }}</label>
					<div class="col-md-9">
						{{ form.pagina_web }}
					</div>
				</div>
			</div><!-- /.box-body -->
		</div><!-- /.box -->
	</div>
</div>
<div class="row">
	<div class="col-md-8">
		<div class="box">
			<div class="box-header with-border">
				<h3 class="box-title">Domicilio</h3>
			</div><!-- /.box-header -->
			<div class="box-body">
				<div class="form-group">
					<label {% if form.municipio.errors %}style="color:red"{% endif %} for="{{ form.municipio.auto_id }}"
					       class="col-md-3 control-label">{{ form.municipio.label }}</label>
					<div class="col-md-9">
						{{ form.municipio }}
					</div>
				</div>
			<div class="form-group">
					<label {% if form.localidad.errors %}style="color:red"{% endif %} for="{{ form.localidad.auto_id }}"
					       class="col-md-3 control-label">{{ form.localidad.label }}</label>
					<div class="col-md-9">
						{{ form.localidad }}
					</div>
				</div>
			<div class="form-group">
					<label {% if form.colonia.errors %}style="color:red"{% endif %} for="{{ form.colonia.auto_id }}"
					       class="col-md-3 control-label">{{ form.colonia.label }}</label>
					<div class="col-md-9">
						{{ form.colonia }}
					</div>
				</div>
			<div class="form-group">
					<label {% if form.calle.errors %}style="color:red"{% endif %} for="{{ form.calle.auto_id }}"
					       class="col-md-3 control-label">{{ form.calle.label }}</label>
					<div class="col-md-9">
						{{ form.calle }}
					</div>
				</div>
			<div class="form-group">
					<label {% if form.numero.errors %}style="color:red"{% endif %} for="{{ form.numero.auto_id }}"
					       class="col-md-3 control-label">{{ form.numero.label }}</label>
					<div class="col-md-9">
						{{ form.numero }}
					</div>
				</div>
			<div class="form-group">
					<label {% if form.codigo_postal.errors %}style="color:red"{% endif %} for="{{ form.codigo_postal.auto_id }}"
					       class="col-md-3 control-label">{{ form.codigo_postal.label }}</label>
					<div class="col-md-9">
						{{ form.codigo_postal }}
					</div>
				</div>
			</div><!-- /.box-body -->
		</div><!-- /.box -->
	</div>
</div>
<div class="row">
	<div class="col-md-8">
		<div class="box">
			<div class="box-header with-border">
				<h3 class="box-title">Responsable</h3>
			</div><!-- /.box-header -->
			<div class="box-body">
<div class="form-group">
					<label {% if form.first_name.errors %}style="color:red"{% endif %} for="{{ form.first_name.auto_id }}"
					       class="col-md-3 control-label">{{ form.first_name.label }}</label>
					<div class="col-md-9">
						{{ form.first_name }}
					</div>
				</div>
			<div class="form-group">
					<label {% if form.last_name.errors %}style="color:red"{% endif %} for="{{ form.last_name.auto_id }}"
					       class="col-md-3 control-label">{{ form.last_name.label }}</label>
					<div class="col-md-9">
						{{ form.last_name }}
					</div>
				</div>
			<div class="form-group">
					<label {% if form.email.errors %}style="color:red"{% endif %} for="{{ form.email.auto_id }}"
					       class="col-md-3 control-label">{{ form.email.label }}</label>
					<div class="col-md-9">
						{{ form.email }}
					</div>
				</div>
			<div class="form-group">
					<label {% if form.username.errors %}style="color:red"{% endif %} for="{{ form.username.auto_id }}"
					       class="col-md-3 control-label">{{ form.username.label }}</label>
					<div class="col-md-9">
						{{ form.username }}
					</div>
				</div>
			<div class="form-group">
					<label {% if form.password.errors %}style="color:red"{% endif %} for="{{ form.password.auto_id }}"
					       class="col-md-3 control-label">{{ form.password.label }}</label>
					<div class="col-md-9">
						{{ form.password }}
					</div>
				</div>

			</div><!-- /.box-body -->
		</div><!-- /.box -->
	</div>
</div>

app/subsistemas/templates/planteles/index.html
{% extends 'base_subsistemas.html' %}

{% load staticfiles %}

{% block extra_head %}
	<link rel="stylesheet" href="{% static "css/misc.css" %}">
{% endblock %}

{% block page_header %}Planteles{% endblock %}
{% block optional_description %}
    <small>Lista</small>{% endblock %}

{% block html %}
    <section class="content">
    <div class="row">
			<div class="col-md-8">
				<div class="toolbar toolbar-border-top">
					<a href="{% url 'subsistemas:planteles_create' %}" class="btn btn-primary">Nuevo plantel</a>
				</div>
			</div>
		</div>
    <div class="row">
            <div class="col-md-8">
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Planteles</h3>
                    </div><!-- /.box-header -->
                    <div class="box-body table-responsive no-padding">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Referencia</th>
                                    <th>CCT</th>
                                    <th>Nivel de demanda</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for plantel in planteles %}
                                    <tr>

                                        <td><a href="{% url 'subsistemas:planteles_edit' plantel.pk %}">{{ plantel.referencia }}</a></td>
                                        <td>{{ plantel.cct }}</td>
                                        <td>{{ plantel.nivel_demanda }}</td>
                                    </tr>
                                {% empty %}
                                    <tr>
                                        <td colspan="4">Sin resultados</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div><!-- /.box-body -->
                    <div class="box-footer">
                        <ul class="pagination pagination-sm no-margin pull-right">
                            {% for p in paginator.page_range %}
                                <li {% ifequal p page_obj.number %} class="active"{% endifequal %}><a
                                        href="?{{ queries.urlencode }}&amp;page={{ p }}">{{ p }}</a></li>
                            {% empty %}
                                <li class="active"><a href="?{{ queries.urlencode }}&amp;page=1">1</a></li>
                            {% endfor %}
                        </ul>
                    </div><!-- box-footer -->
                </div><!-- /.box -->
            </div>
        </div>



    </section>
{% endblock %}

{% block extra_scripts %}{% endblock %}